// Bundles src/main.ts into main.js, and builds styles.css from the shared styles
// (src/styles/*.css) followed by each module's own styles (src/modules/<id>/styles.css, then
// demo.css, the scene of its card in the settings).
// `node esbuild.config.mjs` watches, `node esbuild.config.mjs production` builds once.
import esbuild from "esbuild";
import { builtinModules as builtins } from "node:module";
import fs from "fs";
import path from "path";

const prod = process.argv[2] === "production";
const STYLE_DIR = "src/styles";
const MODULE_DIR = "src/modules";

function cssFiles() {
	const shared = fs
		.readdirSync(STYLE_DIR)
		.filter((f) => f.endsWith(".css"))
		.sort()
		.map((f) => path.join(STYLE_DIR, f));
	const modules = fs
		.readdirSync(MODULE_DIR, { withFileTypes: true })
		.filter((d) => d.isDirectory())
		.flatMap((d) => [path.join(MODULE_DIR, d.name, "styles.css"), path.join(MODULE_DIR, d.name, "demo.css")])
		.filter((f) => fs.existsSync(f))
		.sort();
	return [...shared, ...modules];
}

function buildStyles() {
	const css = cssFiles()
		.map((f) => `/* ${f.replace(/\\/g, "/")} */\n` + fs.readFileSync(f, "utf8").trim())
		.join("\n\n");
	fs.writeFileSync("styles.css", "/* Generated by esbuild.config.mjs from src/styles and src/modules, do not edit. */\n\n" + css + "\n");
}

const stylesPlugin = {
	name: "styles",
	setup(build) {
		build.onEnd(() => buildStyles());
	},
};

const context = await esbuild.context({
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: ["obsidian", "electron", "@codemirror/*", "@lezer/*", ...builtins],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [stylesPlugin],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
	// esbuild only watches what main.ts imports: stylesheets get their own watcher.
	for (const dir of [STYLE_DIR, MODULE_DIR]) {
		fs.watch(dir, { recursive: true }, (_event, file) => {
			if (file && file.endsWith(".css")) buildStyles();
		});
	}
}
